### ISSUE TITLE
Creating non pickable items should go directly to ground

### ISSUE THREAD

**Issue by jahazielhigareda** [OpenCoreMMO/OpenCoreMMO#291]
![image](https://user-images.githubusercontent.com/9941231/153299837-a3727ff2-375d-41d4-9693-4c23798668fb.png)

Ex. 
/i 1015 
/i 1020
/i 1030

**Comment by alissonflyncas** [comment]
Solved by this PR: https://github.com/caioavidal/OpenCoreMMO/pull/307
