### ISSUE TITLE
When you're on top of a pile of rocks you can't use the shovel, and sometimes it works when you're on top of it.

### ISSUE THREAD

**Issue by jahazielhigareda** [OpenCoreMMO/OpenCoreMMO#293]
https://user-images.githubusercontent.com/9941231/153301992-8585041f-f596-461c-a56f-032984c236b7.mp4

**Comment by caioavidal** [comment]
@Lowpoc can u check this one?

**Comment by MarcusSilvaDev** [comment]
I'll see it @caioavidal.

**Comment by MarcusSilvaDev** [comment]
@caioavidal  I tested now and the current release already works fine. I suggest closing the issue.

**Comment by MarcusSilvaDev** [comment]
https://user-images.githubusercontent.com/17841549/181810904-c3c5037c-3cd2-4996-bd66-f7a96d6cee3f.mp4

**Comment by caioavidal** [comment]
> @caioavidal I tested now and the current release already works fine. I suggest closing the issue.

ok. closing
