### ISSUE TITLE
Install Snyk for analytic security

### ISSUE THREAD

**Issue by MarcusSilvaDev** [OpenCoreMMO/OpenCoreMMO#338]
Main: to build a security application and add a pipeline.

Benefits: free for open source project.

Documentation: https://snyk.io/product/snyk-code/

![image](https://user-images.githubusercontent.com/17841549/201414414-0bc3490c-32a0-4478-9355-ee552a4cf6e5.png)
![image](https://user-images.githubusercontent.com/17841549/201414485-f70e5ef4-b624-4031-a5fe-647dafa816b2.png)

**Comment by caioavidal** [comment]
Snyk added to github PR checks
