### ISSUE TITLE
"Player removed from game" message is being displayed 3 times

### ISSUE THREAD

**Issue by MarcusSilvaDev** [OpenCoreMMO/OpenCoreMMO#388]
![image](https://user-images.githubusercontent.com/17841549/206554100-b8df6203-9441-4017-b313-281b019146e7.png)

**Comment by caioavidal** [comment]
How to reproduce: 

1. Start the server
2. Log in as Knight Sample
3. Log out
4. Observe the issue

![image](https://github.com/caioavidal/OpenCoreMMO/assets/11817846/bd0231de-6964-4bbd-8945-bffcc6403d3f)

**Comment by MarcusSilvaDev** [comment]
<img width="518" alt="image" src="https://github.com/caioavidal/OpenCoreMMO/assets/17841549/7d08d898-2ff3-494d-bf4b-4471d00eb5f2">
 
 I validated the problem but not reproduce it. I suggest close issue.
