### ISSUE TITLE
[Command]  !commands - mostra os comandos disponíveis para jogadores no servidor em questão.

### ISSUE THREAD

**Issue by MarcusSilvaDev** [OpenCoreMMO/OpenCoreMMO#439]

**Comment by caioavidal** [comment]
When the player send !commands game should display a window like this:
![image](https://github.com/caioavidal/OpenCoreMMO/assets/11817846/70d68bef-3bf8-499a-8220-9a2c568a8b9e)

**Comment by MarcusSilvaDev** [comment]
Already command for this.

![image](https://github.com/caioavidal/OpenCoreMMO/assets/17841549/f4394329-bc81-4e9e-970f-e2f1fb7774c5)

**Comment by MarcusSilvaDev** [comment]
I'll done this issue.
